import Head from "next/head";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fotawgrafee Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero
        heading='Fotawgrafee'
        message='I take pictures. What else do you want? Hire me.'
      />
      <Slider slides={SliderData} />
    </div>
  );
}
